(cl:in-package arm_lib-msg)
(cl:export '(FIRSTNAME-VAL
          FIRSTNAME
          LASTNAME-VAL
          LASTNAME
          COUNT-VAL
          COUNT
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ALPHA-VAL
          ALPHA
          BETA-VAL
          BETA
          GAMMA-VAL
          GAMMA
          NEWXX-VAL
          NEWXX
          NEWXY-VAL
          NEWXY
          NEWXZ-VAL
          NEWXZ
          NEWYX-VAL
          NEWYX
          NEWYY-VAL
          NEWYY
          NEWYZ-VAL
          NEWYZ
          NEWZX-VAL
          NEWZX
          NEWZY-VAL
          NEWZY
          NEWZZ-VAL
          NEWZZ
          DISTANCE-VAL
          DISTANCE
))