// Generated by gencpp from file arm_gazebo/fkResponse.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_FKRESPONSE_H
#define ARM_GAZEBO_MESSAGE_FKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct fkResponse_
{
  typedef fkResponse_<ContainerAllocator> Type;

  fkResponse_()
    : endX(0.0)
    , endY(0.0)
    , endZ(0.0)  {
    }
  fkResponse_(const ContainerAllocator& _alloc)
    : endX(0.0)
    , endY(0.0)
    , endZ(0.0)  {
  (void)_alloc;
    }



   typedef double _endX_type;
  _endX_type endX;

   typedef double _endY_type;
  _endY_type endY;

   typedef double _endZ_type;
  _endZ_type endZ;





  typedef boost::shared_ptr< ::arm_gazebo::fkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::fkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct fkResponse_

typedef ::arm_gazebo::fkResponse_<std::allocator<void> > fkResponse;

typedef boost::shared_ptr< ::arm_gazebo::fkResponse > fkResponsePtr;
typedef boost::shared_ptr< ::arm_gazebo::fkResponse const> fkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::fkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::fkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::fkResponse_<ContainerAllocator1> & lhs, const ::arm_gazebo::fkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.endX == rhs.endX &&
    lhs.endY == rhs.endY &&
    lhs.endZ == rhs.endZ;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::fkResponse_<ContainerAllocator1> & lhs, const ::arm_gazebo::fkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::fkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::fkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::fkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::fkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::fkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::fkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::fkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3085eb2940cac7695141a9a89c45568a";
  }

  static const char* value(const ::arm_gazebo::fkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3085eb2940cac769ULL;
  static const uint64_t static_value2 = 0x5141a9a89c45568aULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::fkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/fkResponse";
  }

  static const char* value(const ::arm_gazebo::fkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::fkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 endX\n"
"float64 endY\n"
"float64 endZ\n"
"\n"
;
  }

  static const char* value(const ::arm_gazebo::fkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::fkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.endX);
      stream.next(m.endY);
      stream.next(m.endZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::fkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::fkResponse_<ContainerAllocator>& v)
  {
    s << indent << "endX: ";
    Printer<double>::stream(s, indent + "  ", v.endX);
    s << indent << "endY: ";
    Printer<double>::stream(s, indent + "  ", v.endY);
    s << indent << "endZ: ";
    Printer<double>::stream(s, indent + "  ", v.endZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_FKRESPONSE_H
