// Generated by gencpp from file arm_gazebo/ikRequest.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_IKREQUEST_H
#define ARM_GAZEBO_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct ikRequest_
{
  typedef ikRequest_<ContainerAllocator> Type;

  ikRequest_()
    : joint_axis()
    , joint_values()
    , target_values()  {
    }
  ikRequest_(const ContainerAllocator& _alloc)
    : joint_axis(_alloc)
    , joint_values(_alloc)
    , target_values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_axis_type;
  _joint_axis_type joint_axis;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_values_type;
  _joint_values_type joint_values;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _target_values_type;
  _target_values_type target_values;





  typedef boost::shared_ptr< ::arm_gazebo::ikRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::ikRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ikRequest_

typedef ::arm_gazebo::ikRequest_<std::allocator<void> > ikRequest;

typedef boost::shared_ptr< ::arm_gazebo::ikRequest > ikRequestPtr;
typedef boost::shared_ptr< ::arm_gazebo::ikRequest const> ikRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::ikRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::ikRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::ikRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_axis == rhs.joint_axis &&
    lhs.joint_values == rhs.joint_values &&
    lhs.target_values == rhs.target_values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::ikRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "993e8d716df90145069c1ea8a246d997";
  }

  static const char* value(const ::arm_gazebo::ikRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x993e8d716df90145ULL;
  static const uint64_t static_value2 = 0x069c1ea8a246d997ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/ikRequest";
  }

  static const char* value(const ::arm_gazebo::ikRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_axis\n"
"float64[] joint_values\n"
"float64[] target_values\n"
;
  }

  static const char* value(const ::arm_gazebo::ikRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_axis);
      stream.next(m.joint_values);
      stream.next(m.target_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::ikRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_axis[]" << std::endl;
    for (size_t i = 0; i < v.joint_axis.size(); ++i)
    {
      s << indent << "  joint_axis[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_axis[i]);
    }
    s << indent << "joint_values[]" << std::endl;
    for (size_t i = 0; i < v.joint_values.size(); ++i)
    {
      s << indent << "  joint_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_values[i]);
    }
    s << indent << "target_values[]" << std::endl;
    for (size_t i = 0; i < v.target_values.size(); ++i)
    {
      s << indent << "  target_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.target_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_IKREQUEST_H
